# Exported from:        http://Sinthuja:5516/
# Release version:      24.1.0-SNAPSHOT
# Date created:         Wed Apr 17 16:04:26 IST 2024

---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  path: Templates
  home: Digital.ai - Official/Templates
spec:
- directory: "."
  teams:
  - name: Folder Owner
  - name: Viewer
    roles:
    - Authenticated Users
    permissions:
    - folder#view
  - name: Template Owner
    permissions:
    - template#edit_failure_handler
    - template#edit_precondition
    - template#lock_task
  - name: Release Admin
    permissions:
    - release#edit_failure_handler
    - release#edit_precondition
    - release#lock_task
