# Exported from:        http://Sinthuja:5516/
# Release version:      24.1.0-SNAPSHOT
# Date created:         Wed Apr 17 15:57:08 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Templates
  home: Digital.ai - Official/Templates
spec:
- template: Test template2
  scheduledStartDate: 2024-04-17T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: task21
      type: xlrelease.Task
  riskProfile: Default risk profile
  author: admin

